server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/accountdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ACCOUNT-SERVICE
  config:
    import:
      config-server: http://localhost:9226
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-85124564.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaellzhg13JwgO4N5d7
            client-secret: NXYbtP3sTq2kueu6qtmPZxaQ04SzSce6gcHmsMyHziWixXFVBiZyMqbYAOMqN37p
        provider:
          okta:
            issuer-uri: https://dev-85124564.okta.com/oauth2/default

management:
  tracing:
    sampling:
      probability: 1.0